# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none

pool:
  name: Azure Pipelines
  vmImage: windows-latest

steps:
- task: NodeTool@0
  displayName: 'Use Node 18.x'
  inputs:
    versionSpec: 18.x
- script: |
    yarn install
    yarn add @angular/core
    yarn add @angular/compiler     
    yarn add @angular/compiler-cli --dev
    yarn add typescript --dev
    yarn add @angular-devkit/build-angular --dev

- task: Npm@1
  displayName: 'Angular CLI'
  inputs:
    command: custom
    verbose: false
    customCommand: 'install -g @angular/cli' 

- task: Npm@1
  displayName: 'Install dependencies'
  inputs:
    command: install
    workingDir: SocialSphere.UI
    verbose: false

- task: Npm@1
  displayName: 'Build Project'
  inputs:
    command: custom
    workingDir: SocialSphere.UI
    verbose: false
    customCommand: 'run build-prod'
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'
    # pathToPublish: 'SocialSphere.UI\dist'
    # artifactName: 'drop'
    # publishLocation: 'Container'
    