# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none

pool:
  name: Azure Pipelines
  vmImage: windows-latest

steps:
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '18.x'
- script: |
    npm install
    npm i @angular/core
    npm i @angular/compiler  
    npm i @angular/compiler-cli --dev
    npm i typescript --dev
    npm i @angular-devkit/build-angular --dev

- task: Npm@1
  displayName: 'Angular CLI'
  inputs:
    command: custom
    verbose: false
    customCommand: 'install -g @angular/cli' 

- task: Npm@1
  displayName: 'Install dependencies'
  inputs:
    command: install
    workingDir: SocialSphere.UI
    verbose: false

- task: Npm@1
  displayName: 'Build Project'
  inputs:
    command: custom
    workingDir: SocialSphere.UI
    verbose: false
    customCommand: 'run build-prod'
    
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'SocialSphere.UI\dist'
    artifactName: 'drop'
    publishLocation: 'Container'
    