# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'Angular CLI'
  inputs:
    command: custom
    verbose: false
    customCommand: 'install -g @angular/cli' 

- task: Npm@1
  displayName: 'Install dependencies'
  inputs:
    command: ci
    workingDir: SocialSphere.UI
    verbose: false

- task: Npm@1
  displayName: 'Build project'
  inputs:
    command: custom
    workingDir: SocialSphere.UI
    verbose: false
    customCommand: 'run build-prod'
    
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: 'SocialSphere.UI/dist' 
    artifactName: 'drop' 
    publishLocation: 'Container'
    