name: Build the UI project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: Social-Sphere/SocialSphere.UI
        run: npm ci

      - name: Build
        working-directory: Social-Sphere/SocialSphere.UI
        run: npm run build
