name: Build the backend .NET project and run unit tests cases

on:
  pull_request:
    paths-ignore:
      - './SocialSphere.UI/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        working-directory: ./SocialSphere.API
        run: dotnet restore SocialSphere.API.sln

      - name: Build solution
        working-directory: ./SocialSphere.API
        run: dotnet build SocialSphere.API.sln --no-restore

      - name: Test
        working-directory: ./SocialSphere.API
        run: dotnet test SocialSphere.API.sln --no-build
