name: SocialSphereAPI CI/CD

on:
  workflow_dispatch

env:
  AZURE_WEBAPP_NAME: SocialSphereAPI
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  PUBLISH_PACKAGE_PATH: ./SocialSphere.API/publish
  WORKING_DIRECTORY: ./SocialSphere.API

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    - name: Restore
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: dotnet restore ./SocialSphere.API.csproj

    - name: Build
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: dotnet build ./SocialSphere.API.csproj --configuration ${{ env.CONFIGURATION }} --no-restore

    - name: Publish
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: dotnet publish ./SocialSphere.API.csproj --configuration ${{ env.CONFIGURATION }} --no-build --output ./publish

    # Deploy to Azure
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.API_PUBLISH_SECRET }}
        package: ${{ env.PUBLISH_PACKAGE_PATH }}
