name: Sonar Analysis

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: ./SocialSphere.UI


      - name: Sonar Analysis
        run: sonar-scanner
        working-directory: ./SocialSphere.UI

